#
# Copyright (C) 2022 The Android Open Source Project
# Copyright (C) 2022 SebaUbuntu's TWRP device tree generator
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/sts/a04br3
ALLOW_MISSING_DEPENDENCIES := true

PRODUCT_CHARACTERISTICS := tablet

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 := 
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := generic

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := generic
TARGET_CPU_ABI_LIST_64_BIT := $(TARGET_CPU_ABI)
TARGET_CPU_ABI_LIST_32_BIT := $(TARGET_2ND_CPU_ABI),$(TARGET_2ND_CPU_ABI2)
TARGET_CPU_ABI_LIST := $(TARGET_CPU_ABI_LIST_64_BIT),$(TARGET_CPU_ABI_LIST_32_BIT)
TARGET_USES_32_BIT_BINDER := true

# APEX
OVERRIDE_TARGET_FLATTEN_APEX := true

# OTA - WARNING: DO NOT EDIT.
TARGET_OTA_ASSERT_DEVICE := TAB-A04-BR3
BLOCK_BASED_OTA := true

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := a04br3
TARGET_NO_BOOTLOADER := true

# Display

TARGET_SCREEN_WIDTH := 1280
TARGET_SCREEN_HEIGHT := 800

# File systems
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 15728640
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2147483648
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_USES_MKE2FS := true

# Kernel- WARNING: DO NOT EDIT.
BOARD_KERNEL_BASE := 0x40078000
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2 androidboot.selinux=permissive firmware_class.path=/vendor/firmware
BOARD_KERNEL_PAGESIZE := 2048
BOARD_RAMDISK_OFFSET := 0x03f88000
BOARD_KERNEL_TAGS_OFFSET := 0x0df88000
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb # DO NOT EDIT THIS CODE
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_KERNEL_CONFIG := a04br3_defconfig
TARGET_KERNEL_SOURCE := kernel/sts/a04br3
TARGET_KERNEL_CROSS_COMPILE_PREFIX := aarch64-linux-android-

# Vendor partition configure
BOARD_USES_VENDORIMAGE := false

# Platform
TARGET_BOARD_PLATFORM := mt8167
TARGET_BOARD_PLATFORM_GPU := ge8300-mp4

# Recovery - WARNING: DO NOT EDIT.
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/rootdir/recovery/fstab.mt8167
LZMA_RAMDISK_TARGETS := recovery

# Security patch level
VENDOR_SECURITY_PATCH := 2021-08-01

# Hack: prevent anti rollback
#PLATFORM_SECURITY_PATCH := 2099-12-31
#PLATFORM_VERSION := 16.1.0

# mediatek configs
BOARD_USES_MTK_HARDWARE := true
MTK_HARDWARE := true
BOARD_HAS_MTK_HARDWARE := true
ENABLE_CPUSETS := true
ENABLE_SCHEDBOOST := true

# CUSTOM bootimg.mk is not needed!!!
#BOARD_CUSTOM_BOOTIMG_MK := $(DEVICE_PATH)/mkbootimg.mk

# ---  実験的なオプション ---

# Inherit from the proprietary version
-include vendor/sts/a04br3/BoardConfigVendor.mk

# Properties
TARGET_SYSTEM_PROP := $(DEVICE_PATH)/system.prop

# Soong
PRODUCT_SOONG_NAMESPACES += $(DEVICE_PATH)

# Disable AVB
BOARD_AVB_ENABLE := false

# SELinux
#BOARD_SEPOLICY_DIRS := $(DEVICE_PATH)/sepolicy
#BOARD_SEPOLICY_DIRS := \
#	$(LOCAL_PATH)/sepolicy/
#BOARD_SEPOLICY_M4DEFS := \
    public_domain=authr_type \
    mlstrustedsubject=domain
#BOARD_SEPOLICY_VERS := 29
#BOARD_SECCOMP_POLICY += $(DEVICE_PATH)/seccomp
#SELINUX_IGNORE_NEVERALLOWS := true
#WITH_SELINUX := false
